#!/usr/bin/env python3
"""Wrap a translated Boole program into a three-level Strata-Boole file.

    gen_lean.py <fn> <input.rs> <program.boole.st> <out.lean>
                [--level2-only] [--guard <obligations.txt>] [--no-eval]

Level 1: the Verus function, as a comment.
Level 2: the Boole program under `#eval Strata.Boole.verify "cvc5"`; `--guard` pins its
         output with `#guard_msgs`, `--no-eval` drops the check.
Level 3: the Lean theorem (omitted with `--level2-only`).
"""
import re, sys

fn, rs_path, st_path, out_path = sys.argv[1:5]
opts = sys.argv[5:]
level2_only = "--level2-only" in opts
no_eval = "--no-eval" in opts
guard = open(opts[opts.index("--guard") + 1]).read().rstrip("\n") if "--guard" in opts else None
assert not (no_eval and guard), "--no-eval and --guard are mutually exclusive"
rs = open(rs_path).read().split("\n")
st = open(st_path).read().rstrip("\n")

# Verus source: the doc comment + attributes + `pub fn <fn>` … up to the closing
# brace at the function's own indentation.
start = next(i for i, l in enumerate(rs) if re.search(rf"\bfn {re.escape(fn)}\b", l))
indent = len(rs[start]) - len(rs[start].lstrip())
end = next(i for i in range(start + 1, len(rs)) if rs[i] == " " * indent + "}")
b = start
while b > 0 and (rs[b-1].strip().startswith("///") or rs[b-1].strip().startswith("#[")):
    b -= 1
src = "\n".join(l[indent:] if l.startswith(" " * indent) else l for l in rs[b:end+1])
assert "-/" not in src and "/-" not in src

# same name in the guard-only build and the final file: obligation ids carry byte offsets
seed = re.sub(r"[^A-Za-z0-9]", "", fn) + "TranslatedSeed"
guard_block = f"/-- info:\n{guard}\n-/\n#guard_msgs in\n" if guard else ""
eval_block = "" if no_eval else f'{guard_block}#eval Strata.Boole.verify "cvc5" {seed} (options := .quiet)\n'
# A program that uses Boole's native `nat` gets the nat library prepended by
# Strata-Boole, and with it eight obligations about that library.  They are the
# same for every program and are proved by hand.
uses_nat = re.search(r"\b(nat|pos)\b", st) is not None
lib_cases = """  -- Boole's nat library (8 goals, the same for every program).
  case «pos.toInt_body_calls_pos..xO_h_0» | «pos.toInt_body_calls_pos..xI_h_1»
     | pos.toInt_terminates_0 | pos.toInt_terminates_1 =>
    intro p; intros
    cases p <;>
      simp_all [Strata.SMT.DT.pos.is_xH, Strata.SMT.DT.pos.is_xO, Strata.SMT.DT.pos.is_xI,
                Strata.SMT.DT.pos.xO_h, Strata.SMT.DT.pos.xI_h]
  case pos.fromInt_terminates_0 | pos.fromInt_terminates_2 =>  -- 0 ≤ x / 2
    intro x _ h
    exact Int.ediv_nonneg (Int.le_of_lt (Int.lt_trans (by decide) (Int.not_le.mp h))) (by decide)
  case pos.fromInt_terminates_1 | pos.fromInt_terminates_3 =>  -- x / 2 < x
    intro x _ h
    apply Int.ediv_lt_of_lt_mul (by decide)
    rw [Int.mul_comm, Int.two_mul]
    exact Int.lt_add_of_pos_right x (Int.lt_trans (by decide) (Int.not_le.mp h))
""" if uses_nat else ""
level3 = "" if level2_only else f"""
-- Level 3: the same obligations, checked by the Lean kernel.
set_option maxHeartbeats 2000000 in
example : Strata.smtVCsCorrectBoole {seed} := by
  gen_smt_vcs_boole
{lib_cases}  -- The program: cvc5 proves each goal, lean-smt replays the proof in the kernel.
  all_goals (inline_boole_defs; smt (timeout := .some 60))
  -- Bitvector side goals lean-smt leaves behind: `(b ≤ c) = ¬ (c < b)`.
  all_goals (intros; simp only [BitVec.not_lt])
"""
lean = f"""/-
  Copyright Strata Contributors

  SPDX-License-Identifier: Apache-2.0 OR MIT
-/

import StrataBoole.MetaVerifier
import Smt

open Strata

/-
`{fn}` from dalek-lite: Verus to Boole to cvc5 to the Lean kernel.
Generated by `verus-boogie/dalek/rust_to_boole.sh`; do not edit.  See DALEK_BENCHMARK.md.

Level 1: the Verus source.

{chr(10).join("  " + l if l else "" for l in src.split(chr(10)))}
-/

-- Level 2: the Boole program, checked by cvc5.
private def {seed} : StrataDDM.Program :=
#strata
{st}
#end

{eval_block}{level3}"""
open(out_path, "w").write(lean)
print(f"wrote {out_path}")
